openapi: 3.0.3
   info:
  title: STD24089
  version: 1.0.0
servers:
    - url: http://localhost:8000
paths:
  /ping:
  get:
  responses:
  200:
  description: This is aspecification of STD24089
  schema:
  type: string
  example: pong

